#!/usr/bin/env bash

module_sh=$(basename $0)
module_name=${module_sh%.sh}

cat <<"EOF"
Usage: gene $module_name [OPTIONS] COMMAND
*root privileges are necessary

Commands:
  say-hello            Print hello module

Options:
  -h, --help           Show this message

Run 'gene $module_name -h' for more information on a command.
For more details, see man gene.
EOF